### ISSUE TITLE
error with config.yaml

### ISSUE THREAD

**Issue by RobertaBongrani** [italia/spid-testenv2#216]
When I launch python spid-testenv.py I receive this message:

expected a list for dictionary value @ data['metadata']['local']

In my config.yaml file I have:
metadata: 
  local: "./conf/sp_metadata.xml"

Thanks

**Comment by alranel** [comment]
Check the example better, it should be:

```yaml
metadata:
  local:
  - "./conf/sp_metadata.xml"
```
