### ISSUE TITLE
Caricamento SP Metadata via remote

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#229]
C'è qualcosa che non capisco nella configurazione dei metadata del SP tramite caricamento remoto.

Il file config.yaml di esempio nel repository (conf/config.yaml.example#L21 e successive) riporta:

```
#  remote:
#    - "http://spid-sp/metadata"
```

Decommentando la riga però il container non si avvia con errore `ERROR:testenv.log:expected a dictionary @ data['metadata']['remote'][0]`.

Consultando il file testenv/config.py#L41, la struttura del file di config è dichiarata come:

```
           'metadata': {
                'local': All([str], Length(min=0)),
                'remote': All(
                    [
                        {
                            Required('url'): Url(),
                            'cert': str,
                        }
                    ],
                    Length(min=0),
                )
            }
```

Ma se modifico il file di config come dal parser qui sopra, ovvero:

```
metadata:
#  local:
#    - "./conf/sp_metadata.xml"
  remote: 
    - url: 'http://myapp.example.com:17009/SamplePath/Saml2/'
#  db: 'postgresql+psycopg2://postgres:@localhost:5432/exampledb'
```

Il container è correttamente configurato per accedere all'url (verificato tramite wget), ma il loader fallisce il caricamento con errore `testenv.exceptions.MetadataLoadError: La richiesta all'endpoint HTTP '{'url': 'http://myapp.example.com:17009/SamplePath/Saml2/'}': 'No connection adapters were found for '{'url': 'http://myapp.example.com:17009/SamplePath/Saml2/'}''`.

Credo che questo sia dovuto a un typo in https://github.com/italia/spid-testenv2/blob/d0214a43fe73d566679da4c11c52349edbe86a18/testenv/spmetadata.py#L112

che dovrebbe essere `response = requests.get(url['url'])`.

Inoltre sarebbe utile anche correggere il file config.yaml di esempio aggiungendo la chiave `url:` mancante.

Grazie per il supporto
